import {
  AlertTriangle,
  BarChart3,
  Bell,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  Circle,
  Clock,
  Copy,
  CreditCard,
  FileText,
  Home,
  LayoutDashboard,
  Loader2,
  LogOut,
  Mail,
  Menu,
  Moon,
  MoreHorizontal,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Sun,
  Trash2,
  Upload,
  User,
  Users,
  X,
  type Icon as LucideIcon,
} from "lucide-react";

export const Icons = {
  alert: AlertTriangle,
  barChart: BarChart3,
  bell: Bell,
  checkCircle: CheckCircle,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  circle: Circle,
  clock: Clock,
  copy: Copy,
  creditCard: CreditCard,
  fileText: FileText,
  home: Home,
  layoutDashboard: LayoutDashboard,
  loader: Loader2,
  logout: LogOut,
  refresh: RefreshCw,
  mail: Mail,
  menu: Menu,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  plus: Plus,
  search: Search,
  settings: Settings,
  sun: Sun,
  trash: Trash2,
  upload: Upload,
  user: User,
  users: Users,
  x: X,
};

export type Icon = keyof typeof Icons;
